### ISSUE TITLE
关于script

### ISSUE THREAD

**Issue by terryc129** [ant-design/antd-mobile-samples#12]
试了下，script的功能就是把theme.js里的code替换到node_module 的style/index.js。

 1. 请问这么做跟直接在原文件上修改有什么区别？我准备直接在index.js改
 2. 现阶段或者以后会别的方法不用去改node_module么？（类似antd 或者material-ui)

**Comment by paranoidjk** [comment]
你说的自定义主题？

并不是直接改文件，更不能改 node_modules。

自定义主题的原理是 less modify var : http://lesscss.org/usage/#using-less-in-the-browser-modify-variables 是在 runtime 的时候动态改变 less 变量的值，从而影响打包结果。

你也可以新建自己的 theme 文件。

antd-mobile 和 antd 定制主题的方案是一样的 https://ant.design/docs/react/customize-theme-cn

**Comment by terryc129** [comment]
我指的是rn-custom-ui/scripts， 跑完npm start之后的node_module

**Comment by terryc129** [comment]
我之前在antd上有用过定制主题，也有定制component， 但是native没有css

**Comment by silentcloud** [comment]
@terryc129 rn 不去跑 scripts 是不行的，包括 web 也都是在动态更改的，这个避免不了
