### ISSUE TITLE
rn-custom-ui里的自定义主题

### ISSUE THREAD

**Issue by terryc129** [ant-design/antd-mobile-samples#13]
rn-custom-ui/scripts 会直接修改node_module里的style/theme/default.js.

1.  请问这么做跟直接在原文件上修改有什么区别？我准备直接在default.js改
2. 现阶段或者以后会别的方法不用去改node_module么？（类似antd 或者material-ui)

**Comment by paranoidjk** [comment]
请不要重复提issue。

https://github.com/ant-design/antd-mobile-samples/issues/12

**Comment by paranoidjk** [comment]
@silentcloud

**Comment by silentcloud** [comment]
@terryc129  rn 不去跑 scripts 是不行的，包括 web 也都是在动态更改的，这个避免不了

最好不要直接去更改 node_modules， 因为一旦node_modules 做了更新，可能改的就没了

**Comment by terryc129** [comment]
@silentcloud 所以说不管怎么样还是需要更改node_module对吧，如果是这样的我还是在原文件上修改吧，theme.js直接copy style/theme/default.js,每次upgrade时候compare在update回去。
