### ISSUE TITLE
运行create-react-app项目，yarn build 打包错误提示

### ISSUE THREAD

**Issue by MotorFu** [ant-design/antd-mobile-samples#14]
设备：macbook pro
yarn --version 0.24.6
问题：
create-react-app git:(master) ✗ yarn build
yarn build v0.24.6
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

./src/App.js
51:10-16 'antd-mobile' does not contain an export named 'Button'.

error Command failed with exit code 1.

请问是什么问题？求指教

已经解决

**Comment by zlanka** [comment]
Error still persists, any fix?

**Comment by paranoidjk** [comment]
@zlanka Works fine for me, see [official demo](https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app), and [doc](https://mobile.ant.design/docs/react/use-with-create-react-app)

If you got any problems, please file a new issue with reproduible demo.

**Comment by zlanka** [comment]
@paranoidjk there is no antd-mobile inclusion in the [config/webpack.config.prod.js](https://github.com/ant-design/antd-mobile-samples/blob/master/create-react-app/config/webpack.config.prod.js), how would **build** even work? I made **start** work but failed to make **build** work using official documentation mentioned [here](https://mobile.ant.design/docs/react/use-with-create-react-app).
