### ISSUE TITLE
object-assign 顺序不固定引起 checksum warning 的问题

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/antd-mobile-samples#17]
- antd-mobile 目前使用的 [object-assign](https://github.com/sindresorhus/object-assign/blob/master/index.js) 处理了 broswer 和 node 端 react-render-to-string 生成的 props 顺序问题

- 这个 [67e0ee6](https://github.com/ant-design/ant-design-mobile/commit/67e0ee6a985d1e143f3dbbf63988d01a05d67b59) 将 antd-mobile 的 object-assign 包去掉，改成依赖 babel-plugin-transform-assign 来 polyfill， 而 [core-js](https://github.com/zloirock/core-js/blob/master/modules/_object-assign.js) 貌似没处理这个逻辑

@cncolder 有空的时候可以基于这个 demo 检查下最新的 antd-mobile 代码 ssr 是否有 checksum 问题

**Comment by paranoidjk** [comment]
ref: https://github.com/ant-design/ant-design-mobile/issues/1505

rc-tools, antd-tools 都已经添加了 babel-plugin-transform-assign

**Comment by benjycui** [comment]
即使不去掉 warning，至少也要明确告诉开发者哪些版本以下会报 warning。

**Comment by cncolder** [comment]
你是说 core-js 在同一个环境下运行两次也有可能产生不同结果么？react checksum 是指最终的 dom，组件属性顺序会不会影响 dom 输出结果这个还真不清楚。因为我看到 react 生成的 dom 很整齐，总是第一条 class 最后一条 data-reactid。

本来我想增加一个 `.jest.node.json` 配置，最起码做为一个手动备选测试，但是因为 demo 要大量改动，所以没成功。

**Comment by benjycui** [comment]
> 你是说 core-js 在同一个环境下运行两次也有可能产生不同结果么？

不是，是 Node.js 和浏览器生成的结果 key 的顺序不一致。

**Comment by paranoidjk** [comment]
@benjycui 

搞笑了... react 使用的 object-asign 来解决的服务端渲染的props顺序问题.... https://github.com/facebook/react/issues/6451

**Comment by paranoidjk** [comment]
幸亏业务上 react 都用的 umd bundle，不然我去 object-assign 都白干了...

**Comment by benjycui** [comment]
我就奇怪为什么去掉 object-assign 后没有爆 issue。。。不可能用户用的浏览器和 node 都是最新的。。
