### ISSUE TITLE
create-react-app "yarn build" Failed to compile

### ISSUE THREAD

**Issue by zlanka** [ant-design/antd-mobile-samples#20]
**yarn version: 0.24.6**

**Steps followed**
```
$ yarn cache clear
$ git clone git@github.com:ant-design/antd-mobile-samples.git
$ cd antd-mobile-samples/create-react-app
$ yarn install
$ yarn build
```
**Output**
```
yarn build v0.24.6
$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

./src/App.js
51:10-16 'antd-mobile' does not contain an export named 'Button'.

error Command failed with exit code 1.
```

**Comment by warmhug** [comment]
Trace #14

**Comment by paranoidjk** [comment]
Actually, we add notice in the doc:

> Note, we only modified webpack.config.dev.js now, if you wish this config working on production environment, you need to update webpack.config.prod.js as well.

see the https://mobile.ant.design/docs/react/use-with-create-react-app#Web-project
