### ISSUE TITLE
not working in Expo XDE, missing folder

### ISSUE THREAD

**Issue by j2l** [ant-design/antd-mobile-samples#23]
I got:

Error: 'assets/icons/app.png' could not be found, because 'assets/icons' is not a subdirectory of any of the roots  ('E:\Downloads\antd-mobile-samples-master\rn-expo')
    at Promise.all.then.stats (E:/Downloads/antd-mobile-samples-master/rn-expo/node_modules/react-native/packager/src/AssetServer/index.js:181:13)
13:11:50
Error: 'assets/icons/loading.png' could not be found, because 'assets/icons' is not a subdirectory of any of the roots  ('E:\Downloads\antd-mobile-samples-master\rn-expo')
    at Promise.all.then.stats (E:/Downloads/antd-mobile-samples-master/rn-expo/node_modules/react-native/packager/src/AssetServer/index.js:181:13)
13:11:50
Building JavaScript bundle: error
Unable to resolve module `../../../../App` from `E:\Downloads\antd-mobile-samples-master\rn-expo\node_modules\react-native-scripts\build\bin\crna-entry.js`: Directory E:\Downloads\antd-mobile-samples-master\rn-expo\App doesn't exist

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/28505837-a6bbab44-7059-11e7-804a-8498c1721e93.png)

**Comment by silentcloud** [comment]
`assets/icons/app.png` file is not used in the code

**Comment by paranoidjk** [comment]
<img width="591" alt="2017-07-24 10 52 15" src="https://user-images.githubusercontent.com/7971415/28506452-2e207a8e-705e-11e7-8b4e-a02f80a5e347.png">

@silentcloud

**Comment by silentcloud** [comment]
@paranoidjk yarn or npm install ？

**Comment by j2l** [comment]
npm install in my case. Win10. Latest Expo XDE.
Warnings about "not using the Expo fork" are not important. I read (but can't find), this warning will be removed soon.

I got errors, not just warnings:
![image](https://user-images.githubusercontent.com/65325/28511758-d758f4ce-704e-11e7-8db2-cddfda3eca9e.png)

Thanks for your help.

**Comment by silentcloud** [comment]
@j2l I don't have android device, I have test it with my iPhone, the error doesn't appear.

![image](https://user-images.githubusercontent.com/1698185/28512493-b2e1f448-7084-11e7-9823-a37c88ecb4dc.png)

Please use Expo XDE to init a empty project, be sure if you can run.

**Comment by j2l** [comment]
Expo XDE successfully init projects. I succesfully tested RNE and native-base already. Only AntD-Mobile is not working.

**Comment by j2l** [comment]
Your locale-provider seems great :)

**Comment by silentcloud** [comment]
@j2l Can you run  online demo?

![image](https://user-images.githubusercontent.com/1698185/28512702-90a977ba-7085-11e7-8097-4c68986956f4.png)

**Comment by j2l** [comment]
It works fine.

**Comment by j2l** [comment]
Adding /Assets/icons folder from another project fix this.
One of the missing icon is https://github.com/StephenGrider/AdvancedReactNative/blob/master/jobs/assets/icons/app.png

Hmm, may be AntiVirus is the cause in my case as [noted by some Node.js users](https://github.com/Medium/phantomjs/issues/19). A/V hates an exe (Expo or Node or else) to create files and may stop when exe is downloading/creating files too fast (1GBps in my case).
I switch to Linux.

**Comment by j2l** [comment]
Now I have: 
![screenshot_2017-07-24-13-36-56](https://user-images.githubusercontent.com/65325/28521724-367c6d8e-7075-11e7-8169-57982cea9a8f.png)

I fixed it by http://facebook.github.io/react-native/docs/upgrading.html#content

Now, I get a missing FOLDER named alipay@3x.png
I guess it resolves as a file on Mac, not on Windows.
I fixed it changing antd-mobile-samples-master\rn-expo\components\result\demo\basic.js to:
```
import React from 'react';
import { ScrollView, Text, Image } from 'react-native';
import { Result } from 'antd-mobile';
export default class ResultExample extends React.Component {
    render() {
        return (<ScrollView style={{ backgroundColor: '#F5F5F9', flex: 1 }}>
      <Text style={{ margin: 10, color: '#999' }}>URI 图片</Text>
      <Result imgUrl={{ uri: 'https://zos.alipayobjects.com/rmsportal/GcBguhrOdlYvGfnsXgrE.png' }} title="验证成功" message="所提交内容已成功完成验证"/>

      <Text style={{ margin: 10, color: '#999' }}>Image source</Text>
	<Result imgUrl={{ uri:'./alipay@3x.png'}} title="验证成功" message="所提交内容已成功完成验证"/>

      <Text style={{ margin: 10, color: '#999' }}>Image element</Text>
	<Result imgUrl={{ uri:'./alipay@3x.png'}} style={{ width: 60, height: 60 }} title="验证成功" message={<Text>所提交内容已成功完成验证</Text>}/>

      <Text style={{ margin: 10, color: '#999' }}>含 button 操作</Text>
	<Result imgUrl={{ uri:'./alipay@3x.png'}} style={{ width: 60, height: 60 }} title="验证成功" message="所提交内容已成功完成验证" buttonText="完成" buttonType="primary" buttonClick={e => alert(e.toString())}/>
    </ScrollView>);
    }
}
```
Finally I get:
![screenshot_2017-07-24-14-21-58](https://user-images.githubusercontent.com/65325/28523334-37751676-707c-11e7-9dee-3f89e20d997e.png)
which seems related to a dependency:
https://github.com/react-native-community/react-native-svg/issues/401

Looks like dependencies make this project very fragile.

**Comment by silentcloud** [comment]
`rn-demo` is created with [create-react-native-app](https://github.com/react-community/create-react-native-app), you can follow [the doc: use-with-create-react-app](https://mobile.ant.design/docs/react/use-with-create-react-app#Import-antd-mobile)  to create an 
empty project, then add the `rn-demo` code

**Comment by paranoidjk** [comment]
Close since problem can not reproduce, so we actually can not offer help for you, sorry.

**Comment by j2l** [comment]
@silentcloud you mean `rn-expo`, right?

OK, I tried creating a brand new project with Expo XDE (WIN 10, not MAC), it starts OK, no error.
Then, following [instructions](https://mobile.ant.design/docs/react/use-with-create-react-app#Import-antd-mobile):

`npm i babel-plugin-import --only=dev`, ok
`npm i antd-mobile`, ok
`npm run eject`, doesn't work: "missing script eject"
`npm i svg-sprite-loader@0.3.1 less less-loader postcss-pxtorem`, ok
`config/webpack.config.dev.js` doesn't exist
copied `/components, /src, /_tests_` and `App.js` from antd-mobile-samples
modified` .babelrc` to add:
```
  "presets": ["babel-preset-expo"],
    "plugins": [["import", { "libraryName": "antd-mobile" }]],
  "env": {
```
restart XDE, missing react-navigation
`npm i react-navigation`, ok
restart XDE, missing iconfont.ttf, 
adding them from antd-mobile-samples
restart XDE, missing antd-mobile-demo-data
`npm i antd-mobile-demo-data`, ok
restart XDE, wrong babel-plugin-import :(
`npm i babel-plugin-import`, ok
restart XDE, wrong babel-plugin-import :(
![screenshot_2017-07-25-16-16-58](https://user-images.githubusercontent.com/65325/28577320-b92f4148-7156-11e7-835d-f300dacf5a43.png)
Aaaargh!

@paranoidjk I don't see someone tried on Windows so far, could you reopen it until someone tries with Windows 10? Thanks.
