### ISSUE TITLE
Update create-react-app example

### ISSUE THREAD

**Issue by goran-paunovic** [ant-design/antd-mobile-samples#27]
Please, update your example so it works with latest version of create-react-app utility.

**Comment by j2l** [comment]
+1, and expo

**Comment by silentcloud** [comment]
`rn-expo` will be updated after antd-mobile@2.0

**Comment by j2l** [comment]
@silentcloud  thanks.
The issue is how to "npm install" babel-plugin from your github project.
Not an update of rn-expo sample

**Comment by j2l** [comment]
Hope we won't need to EJECT

**Comment by silentcloud** [comment]
@j2l antd-mobile@2.0
