### ISSUE TITLE
在android 4.0 ,4.3下都是显示空白，其他高版本和苹果ios没有问题。

### ISSUE THREAD

**Issue by szwork2013** [ant-design/antd-mobile-samples#29]
在android 4.0 ,4.3下都是显示空白，其他高版本和苹果ios没有问题。
在roadhog 和dva 组合的脚手架下也是出现同样问题。

望提示！急急！在线等。。。。。

**Comment by paranoidjk** [comment]
Web 还是 ReactNative ? 空白具体是指页面什么问题？

请给出可复现的 demo 和具体机型以及复现步骤。

**Comment by szwork2013** [comment]
web的，三星9100,三星note3，用roadhog 和dva 组合的脚手架测试简单显示某个antd-mobile2 实验版本的组件;或antd-mobile-samples下web-webpack2项目:https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack2复现,就是什么也不显示；
但是用以上的设备访问http://beta.mobile.ant.design/kitchen-sink则是正常的。

**Comment by szwork2013** [comment]
@paranoidjk 你可找一台android4.0至4.4版本的机器测试一下官方测试项目：
https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack2

**Comment by szwork2013** [comment]
出现的情况如上描述：页面什么也不显示，是空的。

**Comment by szwork2013** [comment]
测试的版本："antd-mobile": "^2.0.0-alpha.9"

**Comment by szwork2013** [comment]
把这个案例：https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app

中的antd-mobile1.6.5修改"antd-mobile": "^2.0.0-alpha.9"测试，倒是正常显示的。

**Comment by szwork2013** [comment]
@paranoidjk 总结一下：
1.把这个案例：https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app
中的antd-mobile1.6.5修改"antd-mobile": "^2.0.0-alpha.9"测试，倒是正常显示的。
2. https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack2
显示空白，不正常。
3.用roadhog(1.22) 和dva(2.0.1) 组合的脚手架，测试antd-mobile": "^2.0.0-alpha.9"
显示空白，不正常。

**Comment by paranoidjk** [comment]
duplicate with https://github.com/sorrycc/roadhog/issues/417
