### ISSUE TITLE
rn-custom-ui theme.js really work?

### ISSUE THREAD

**Issue by ouzhou** [ant-design/antd-mobile-samples#3]
![image](https://cloud.githubusercontent.com/assets/7693866/24837423/34711286-1d66-11e7-8f90-e45e22e159f4.png)
i guess you want a red tag with green border
but it seems doesn't work

**Comment by silentcloud** [comment]
please `npm start`

![test](https://cloud.githubusercontent.com/assets/1698185/24851870/d44fefd8-1e07-11e7-8d0f-fb12db13c94e.gif)
