### ISSUE TITLE
sorry,we don't have 'config/' folder name to modify when we use create-react-app...

### ISSUE THREAD

**Issue by CocoChen917** [ant-design/antd-mobile-samples#30]
webpack.config.dev.js  (path: node_modules/react-scripts/config);should i modify it?

**Comment by paranoidjk** [comment]
you may need to run npm run eject first.

**Comment by afc163** [comment]
https://ant.design/docs/react/use-with-create-react-app

We don't recommend ejecting now.

**Comment by paranoidjk** [comment]
https://github.com/timarney/react-app-rewired#2-create-a-config-overridesjs-file-in-the-root-directory

@afc163 looks like atool-build usage, configuration file is a function, `webpack config --> create-react-app-config --> react-app-rewired config`, i am worried about the version upgrade issue in this way.

**Comment by silentcloud** [comment]
@afc163 What is the reason？

**Comment by afc163** [comment]
The eject config is changed when cra is upgraded, it is hard to maintain a documentation that always works.
