### ISSUE TITLE
Cannot find module 'less'

### ISSUE THREAD

**Issue by KingBarbarian** [ant-design/antd-mobile-samples#33]
-  `git clone https://github.com/ant-design/antd-mobile-samples`

- `cd create-react-app`

- `yarn install`

- `yarn start`

`Module build failed: Error: Cannot find module 'less'` why?

**Comment by silentcloud** [comment]
I cannot reproduce

**Comment by huyifan** [comment]
how to resolve this problem?
I met the same error

**Comment by huyifan** [comment]
well~I have fixed it by adding 'npm install less -save-dev'
hope can help you

**Comment by silentcloud** [comment]
My fault, I have installed `less` globally, so I could not reproduce.

Thanks @zhang740 @KingBarbarian
