### ISSUE TITLE
完全不行啊

### ISSUE THREAD

**Issue by buzai** [ant-design/antd-mobile-samples#36]
ubuntu16 node7.10

运行 yarn start
```
yarn start v1.0.2
$ react-native-scripts start
1:37:23 PM: Starting packager...
Done in 26.94s.
```

运行 npm run android 之后就卡在这，过一会就没有提示的停掉了
```
> antm-expo@0.1.0 android /mydata/code/antd-mobile-samples/create-react-native-app
> react-native-scripts android

1:37:49 PM: Starting packager...

```

我用 react native init 的工程在我本机模拟器跑得了，我直接git clone 了这个不行了

**Comment by silentcloud** [comment]
react-react-native-app 里面集成的有 expo，expo 被墙的可能很大，我这边都是要 V*P*N 才能跑起的，你设置一下你 terminal 的代理，就可以了 @buzai
