### ISSUE TITLE
在ie10和qq浏览器显示空白

### ISSUE THREAD

**Issue by zhihuihu** [ant-design/antd-mobile-samples#41]
- antd-mobile 版本：2.0
- 操作系统及其版本：
安卓7.0的QQ浏览器和ie10浏览器

手机QQ浏览器直接显示空白，

ie10报错
![image](https://user-images.githubusercontent.com/16135245/32998810-1f1d536c-cdd9-11e7-8c73-1394679b53ab.png)

**Comment by zhihuihu** [comment]
用得create react app工具创建的

**Comment by paranoidjk** [comment]
自己先排查下空白原因？ console 是否有报错？

什么项目？直接访问 https://mobile.ant.design/index-cn 测试一下？

**Comment by zhihuihu** [comment]
@paranoidjk 这个可以访问，

我自己写的例子console报错了，如上图截图，是不是我的babel有问题，create-react-app的配置没有动过直接打包的
![image](https://user-images.githubusercontent.com/16135245/33003910-b5027f28-cdf8-11e7-9297-dda5b12048fb.png)

**Comment by paranoidjk** [comment]
https://reactjs.org/blog/2017/09/26/react-v16.0.html#javascript-environment-requirements
