### ISSUE TITLE
关于 webpack loader 选择的疑问

### ISSUE THREAD

**Issue by jasonslyvia** [ant-design/antd-mobile-samples#45]
在 README 中提到

> TypeScript-react 官方教程里提供的 awesome-typescript-loader 建议不要使用，建议改用 ts-loader

请问是否有什么具体的限制或问题？

**Comment by warmhug** [comment]
当时有问题，现在如果没问题也可以用，欢迎测试反馈

**Comment by jasonslyvia** [comment]
了解，谢谢
