### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by kevin0137** [ant-design/antd-mobile-samples#5]
`antm-roadhog`中本机访问`localhost:8001`没问题
想用手机测一测效果 在移动端输入本机ip 比如`http://192.168.1.144:8001`
页面出现的是`Invalid Host header`
请问什么原因会导致这种问题?

**Comment by paranoidjk** [comment]
可能是你手机和PC不在同一个局域网，比如同一个wifi下。

**Comment by kevin0137** [comment]
是在同一网段下的
在本机把localhost改为本机ip也会出现这种情况

**Comment by paranoidjk** [comment]
除了 antm-roadhog 之外其他demo有这个问题么？

**Comment by kevin0137** [comment]
我只测了`antm-roadhog` 和 `web-dvajs`
dva是正常的

估计是roadhog的问题 以前用dora没出现这类情况

**Comment by paranoidjk** [comment]
抱歉，最近比较忙，可能没时间处理这个。
你可以研究下有解决方案欢迎给我们PR，也可以去roadhog 提个 issue。

**Comment by kevin0137** [comment]
嗯好
