### ISSUE TITLE
可以出一个egg的用例?

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/antd-mobile-samples#8]
感觉阿里公司的egg和antd都是很棒的开源产品, 要是结合起来就很完美了!
用的过程中,缺少参考! 
如果官方有这样的例子,简直是美极了!~

**Comment by junmaqiang** [comment]
亲爱的,我很需要你 @paranoidjk

**Comment by paranoidjk** [comment]
这个没什么特别的，你参考 https://github.com/eggjs/examples 应该就行了。

**Comment by paranoidjk** [comment]
https://github.com/eggjs/egg/issues/328
