### ISSUE TITLE
"@ant-design/react-native": "^3.0.3" 自定义主题说明是旧版本的

### ISSUE THREAD

**Issue by davidfang** [ant-design/antd-mobile-samples#81]
- antd-mobile 版本："@ant-design/react-native": "^3.0.3"
- 浏览器 (或标明是 react-native) 及其版本："@ant-design/react-native": "^3.0.3"
- 操作系统及其版本：

无法自定义主题，目前文档上的自定义主题只是1和2版本的，最3版本无法自定义主题，请处理

**Comment by SuGod** [comment]
3.x 改了包名了，只需要把 `antd-mobile-rn` ==> `@ant-design/react-native`
```javascript
const defaultVars = require('@ant-design/react-native/lib/style/themes/default')
const themePath = path.resolve(require.resolve('@ant-design/react-native'), '../style/themes/default.js')
```

**Comment by klaZzz** [comment]
请问3.x 如何自定义样式

**Comment by chakwo009** [comment]
> 3.x 改了包名了，只需要把 `antd-mobile-rn` ==> `@ant-design/react-native`
> 
> ```js
> const defaultVars = require('@ant-design/react-native/lib/style/themes/default')
> const themePath = path.resolve(require.resolve('@ant-design/react-native'), '../style/themes/default.js')
> ```

也是不行，求解

**Comment by Wuguanghua** [comment]
求解 +1

**Comment by xtlog** [comment]
这个问题还是没有解决吗？  
3.X版本上确实无法修改样式，能不能有人出来说明一下？

**Comment by BANG88** [comment]
@xtlog 3.0.0 重构了，样式覆盖可以查看 https://rn.mobile.ant.design/docs/react/upgrade-notes-cn#3.0.0

现在支持通过Provider覆盖部分样式。
